Ros:
  node_name: "grace_sensor_interface"
  queue_size: 100
  dynamic_reconfig_request_timeout: 0.5

  camera_cfg_server: "/hr/perception/camera_angle"
  camera_angle_topic: "/grace_proj/set_cam_angle"

  asr_words_topic: "/hr/perception/hear/words"
  asr_interim_speech_topic: "/hr/perception/hear/interim_speech"
  asr_fake_sentence_topic: "/hr/perception/hear/fake_sentence"
  asr_reconfig: "/hr/perception/speech_recognizer"

  vad_config: "/hr/perception/whisper_asr"


  dynam_config_timeout: 0.5


Vision:
  default_grace_chest_cam_angle: 0.35


ASR:
  #ASR Configs
  english_language_code: &id_lang_eng 'en-US' 
  cantonese_language_code: &id_lang_yue 'yue-Hant-HK' 
  primary_language_code: *id_lang_eng
  secondary_language_code: *id_lang_yue

  asr_fake_sentence_check_rate: 30
  asr_fake_sentence_window: 1
  #Since we have vad now we stop continuous listening 
  asr_continuous: false
  asr_model: "latest_long"
